package com.trkn.level2.collectionFinalPractice.first;

import static com.trkn.level2.collectionFinalPractice.first.StringUtil.getUniqueWords;

public class Main {
    public static void main(String[] args) {
        String text = "In the heart of a bustling city, with skyscrapers towering above and streets constantly alive with the hum of traffic, there lies a park—a hidden sanctuary from the fast pace of daily life. The sound of rustling leaves and the soft chirping of birds offer a calming contrast to the constant noise of urban existence. People of all walks of life come here to escape the pressures of the world, whether it’s to sit quietly by a pond, read a book under the shade of an old oak tree, or take a leisurely stroll along winding pathways. The park has been a part of the city for generations, with its roots tracing back to a time when the area was just an open field, used by farmers to graze their cattle. Over the years, as the city grew, the park became a hub for the community—a place for people to gather, to celebrate, and to find moments of peace amid the chaos. Today, it stands as a testament to nature’s resilience, a rare green space that has managed to withstand the encroaching developments surrounding it. Children can often be seen playing in the playground, their laughter filling the air as they swing higher and higher, reaching for the sky. Nearby, an old fountain that once served as the centerpiece of a grand estate now stands proudly as a reminder of the park’s rich history. The stonework, though weathered, still carries the intricate carvings of a bygone era, while the water flows gently over its edges, creating a soothing melody that adds to the tranquility of the space. As the sun begins to set, casting a warm golden hue across the landscape, the park takes on a new character. The long shadows of trees stretch across the grass, and the cool evening breeze carries with it the scent of flowers that have just begun to bloom. People begin to gather for evening walks or casual meet-ups with friends, enjoying the last moments of daylight before the city’s neon lights take over the night.";
        getUniqueWords(text).forEach((key, value) -> System.out.println(key + " - " + value));
    }
}
